#!/usr/bin/env bash
# Generated by scripts/build.ts. Do not edit.
# Hue tmux theme — TPM entrypoint. Select a mood with:
#   set -g @hue_flavour 'mua'   # or 'huong' / 'cung'

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
flavour="$(tmux show-option -gqv @hue_flavour)"
[ -z "$flavour" ] && flavour="mua"

theme="$CURRENT_DIR/themes/hue-$flavour.conf"
if [ -f "$theme" ]; then
  tmux source-file "$theme"
else
  tmux display-message "hue-tmux: unknown @hue_flavour '$flavour'"
fi
